// The only module in this app allowed to know Blueprint's raw JSON shape.
// Everything else in workout-logger must go through BlueprintAdapter and
// refer to Blueprint entities by their stable `id`, never by display name.
//
// Data source: a vendored, versioned snapshot at src/blueprint/snapshot/
// (see manifest.json for provenance), regenerated by
// `npm run sync-blueprint`. This app never fetches Blueprint at request
// time — see docs/architecture.md for why.

import exercisesSnapshot from './snapshot/exercises.json' with { type: 'json' };
import programmingSnapshot from './snapshot/programming.json' with { type: 'json' };
import manifest from './snapshot/manifest.json' with { type: 'json' };
import type {
  BlueprintAestheticOutcome,
  BlueprintEquipment,
  BlueprintExercise,
  BlueprintFunctionalGoal,
  BlueprintManifest,
  BlueprintPhysiqueTarget,
  BlueprintProgramming,
} from './types.js';

function deepFreeze<T>(value: T): T {
  if (value !== null && (typeof value === 'object' || typeof value === 'function')) {
    for (const key of Object.getOwnPropertyNames(value)) {
      deepFreeze((value as Record<string, unknown>)[key]);
    }
    Object.freeze(value);
  }
  return value;
}

const exercises = deepFreeze(exercisesSnapshot as unknown as BlueprintExercise[]);
const programming = deepFreeze(programmingSnapshot as unknown as BlueprintProgramming);

const exercisesById = new Map<string, BlueprintExercise>(exercises.map((e) => [e.id, e]));
const aestheticGoalsById = new Map<string, BlueprintAestheticOutcome>(
  programming.aestheticOutcomes.map((g) => [g.id, g])
);
const functionalGoalsById = new Map<string, BlueprintFunctionalGoal>(
  programming.functionalGoals.map((g) => [g.id, g])
);
const targetsById = new Map<string, BlueprintPhysiqueTarget>(
  programming.physiqueTargets.map((t) => [t.id, t])
);

const equipmentCounts = new Map<string, number>();
for (const exercise of exercises) {
  for (const item of exercise.equipment) {
    equipmentCounts.set(item, (equipmentCounts.get(item) ?? 0) + 1);
  }
}
const equipmentList: BlueprintEquipment[] = [...equipmentCounts.entries()]
  .map(([id, exerciseCount]) => ({ id, exerciseCount }))
  .sort((a, b) => a.id.localeCompare(b.id));
const equipmentById = new Map<string, BlueprintEquipment>(equipmentList.map((e) => [e.id, e]));

/**
 * Read-only access to Blueprint's knowledge layer (exercises, targets,
 * goals, equipment). Every lookup returns `undefined` for an unknown id
 * rather than throwing — callers decide whether a missing reference is
 * fatal for their use case.
 *
 * All returned objects are frozen at snapshot load time via the JSON
 * import itself (see immutability note in adapter tests) — this module
 * never mutates them.
 */
export const BlueprintAdapter = {
  getExercise(id: string): BlueprintExercise | undefined {
    return exercisesById.get(id);
  },

  getExercises(): readonly BlueprintExercise[] {
    return exercises;
  },

  getAestheticGoal(id: string): BlueprintAestheticOutcome | undefined {
    return aestheticGoalsById.get(id);
  },

  getAestheticGoals(): readonly BlueprintAestheticOutcome[] {
    return programming.aestheticOutcomes;
  },

  getFunctionalGoal(id: string): BlueprintFunctionalGoal | undefined {
    return functionalGoalsById.get(id);
  },

  getFunctionalGoals(): readonly BlueprintFunctionalGoal[] {
    return programming.functionalGoals;
  },

  getTarget(id: string): BlueprintPhysiqueTarget | undefined {
    return targetsById.get(id);
  },

  getTargets(): readonly BlueprintPhysiqueTarget[] {
    return programming.physiqueTargets;
  },

  getEquipment(id: string): BlueprintEquipment | undefined {
    return equipmentById.get(id);
  },

  getEquipmentList(): readonly BlueprintEquipment[] {
    return equipmentList;
  },

  /** True if `id` resolves to a real Blueprint exercise. */
  isKnownExercise(id: string): boolean {
    return exercisesById.has(id);
  },

  getManifest(): BlueprintManifest {
    return deepFreeze(manifest) as BlueprintManifest;
  },
};

export type { BlueprintAestheticOutcome, BlueprintEquipment, BlueprintExercise, BlueprintFunctionalGoal, BlueprintPhysiqueTarget };
